cart/urls.py
from django.urls import path
from .views import cart_detail, update_cart_by_front, remove_product, remove_cart, get_cart_length, remove_product_ajax

app_name = 'cart'

urlpatterns = [
    path('detail/', cart_detail, name='cart_detail'),
    path('update_cart_session/', update_cart_by_front, name='update_cart_session'),
    path('remove_fetch/', remove_product_ajax, name="remove_product_ajax"),
    path('remove/<int:product_id>/', remove_product, name="remove_product"),
    path('clear/', remove_cart, name="remove_cart"),
    path('length/', get_cart_length, name="cart_length"),
]

orders/urls.py
from django.urls import path
from .views import new_quick_order, new_order, orders_list, order_detail

urlpatterns = [
    path('new/', new_order, name="new_order"),
    path('new/quick/', new_quick_order, name="new_quick_order"),
    path('list/', orders_list, name="orders"),
    path('detail/<str:number>/', order_detail, name="order_detail"),
]

shop/urls.py
from django.urls import path
from .views import (ProductListView, ProductCreateView, ProductDetailView,
                    ProductUpdateView, ProductDeleteView,
                    CategoryCreateView, CategoryListView, CategoryDetailView,
                    CategoryUpdateView, CategoryDeleteView)
from .views import ProductListByCategory, product_search, about
# from .views import product_list_view
from cart.views import cart_add

app_name = 'shop'

urlpatterns = [
    # path('categories/<slug:slug>/products/test/', product_list_view, name='test'),

    path('about/', about, name='about'),

    path('categories/add/', CategoryCreateView.as_view(), name='category_add'),
    path('categories/<slug:slug>/edit/', CategoryUpdateView.as_view(), name='category_edit'),
    path('categories/<slug:slug>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('categories/<slug:slug>/products/', ProductListByCategory.as_view(), name='products_by_category'),
    path('categories/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('categories/', CategoryListView.as_view(), name='categories'),

    path('search/', product_search, name='product_search'),
    path('search/<str:category>/', product_search, name="product_search"),
    path('search/all/', product_search, name="product_search"),



    path('list/', ProductListByCategory.as_view(), name='products'),
    path('add/', ProductCreateView.as_view(), name='product_add'),
    path('<slug:slug>/edit/', ProductUpdateView.as_view(), name='product_edit'),
    path('<slug:slug>/addToCart/', cart_add, name='add_to_cart'),
    path('<slug:slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),


    path('', ProductListByCategory.as_view(), name='index'),


]

website_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop.views import AdminTemplateView, ProductListByCategory
from website_shop import settings
from orders.views import all_order_list

urlpatterns = [
    path('staff/orders/', all_order_list, name="admin_all_orders"),
    path('staff/', AdminTemplateView.as_view(), name="admin-page"),
    path('admin/', admin.site.urls),
    path('products/', include('shop.urls')),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', ProductListByCategory.as_view(), name='main'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = "shop.views.forbidden"
handler404 = "shop.views.page_not_found"
handler500 = "shop.views.server_error"

shop/forms.py
from django import forms
from .models import Category, Product


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description', 'image_1', 'image_2']


class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ('slug', 'created', 'updated')

        labels = {
            'category': 'Категория',
            'description': 'Описание',
            'image': 'Изображение',
            'available': "Доступность товара",
            'price': 'Цена',
        }

orders/views.py
import uuid
import json

from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404, redirect, reverse, render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from django.views.generic import ListView, DetailView
from django.contrib.auth import get_user_model

from .models import Order, OrderItem
from .forms import OrderForm
from cart.views import Cart, ProductCartUser
from cart.models import CartItem
from shop.models import Product


user = get_user_model()



@csrf_exempt
def new_quick_order(request):
    data = json.loads(request.body)
    name = data.get('name')
    last_name = data.get('lastName')
    email = data.get('email')
    phone = data.get('phone')
    delivery = data.get('delivery')
    payment = data.get('payment')

    cart = Cart(request)

    order = Order.objects.create(name=name,
                                 last_name=last_name,
                                 email=email,
                                 phone=phone,
                                 delivery=delivery,
                                 payment=payment,
                                 number=uuid.uuid4(),
                                 )

    for item in cart:
        OrderItem.objects.create(order=order, product=item['product'], quantity=item['quantity'])

    # orders = OrderItem.objects.filter(order=order)
    # cart_order = cart.copy()
    cart.clear()

    url = reverse("main")
    json_response = {"status": "ok", "url": url}
    return JsonResponse(json_response)
    # return render(request, template_name='orders/order_create.html', context={'cart_order': cart_order})


def new_order(request):
    cart = ProductCartUser(request)

    if request.method == "GET":
        order_form = OrderForm()
        context = {"form": order_form}
        return render(request, template_name='orders/order_add.html', context=context)

    if request.method == "POST":
        order_form = OrderForm(request.POST)

        if order_form.is_valid():
            order = order_form.save(commit=False)
            order.number = uuid.uuid4()
            order.user = request.user
            order.cart = cart.user_cart
            order.name = request.user.username
            order.last_name = request.user.last_name
            order.email = request.user.email
            order.phone = request.user.phone

            order.save()

            for item in cart:
                OrderItem.objects.create(order=order_form.instance, product=item['product'], quantity=item['quantity'])

            cart.user_cart.delete()

        context = {"order": order_form.instance}
        return render(request, template_name='orders/order_create.html', context=context)


@login_required
def orders_list(request):
    admin = user.objects.get(username='staff')
    if request.user == admin:
        orders = Order.objects.all()
        context = {"orders": orders, "current_page": 'orders',}
        return render(request, template_name='orders/orders.html', context=context)

    orders = Order.objects.filter(user=request.user)
    context = {
        "orders": orders,
    }

    return render(request, template_name='orders/orders.html', context=context)

@login_required
def order_detail(request, number):
    admin = user.objects.get(username='staff')
    if request.user == admin:
        order = get_object_or_404(Order, number=number)
        order_items = order.order_items.all()
        count = 0
        for item in order_items:
            count += item.product.price
        context = {"order": order, "order_items": order_items, "count": count}
        return render(request, template_name='orders/admin/order_detail.html', context=context)

    order = get_object_or_404(Order, number=number, user=request.user)
    order_items = order.order_items.all()
    count = 0
    for item in order_items:
        count += item.product.price

    context = {"order": order, "order_items": order_items, "count": count}

    return render(request, template_name='orders/order_detail.html', context=context)


# class OrderListView(ListView):
#     model = Order
#     template_name = 'shop/admin/orders.html'
#     context_object_name = 'orders'
#
#
# class OrderDetailView(DetailView):
#     model = Order
#     template_name = 'orders/order_detail.html'
#     context_object_name = 'order'
#     slug_field = 'number'
#     slug_url_kwarg = 'number'

def all_order_list(request):
    admin = user.objects.get(username='staff')
    if request.user != admin:
        raise PermissionError

    print(type(admin))

    orders = Order.objects.all()
    context = {"orders": orders}

    return render(request, template_name='shop/admin/orders.html', context=context)

shop/views.py
from django.views.generic import (ListView, CreateView,
                                  UpdateView, DetailView,
                                  DeleteView, TemplateView)
from django.core.paginator import Paginator

from django.urls import reverse_lazy
from django.db.models import Q
from django.shortcuts import get_object_or_404, render

from .models import Product, Category
from .forms import CategoryCreateForm, ProductCreateForm
from .filters import ProductFilter
from django.contrib.auth import get_user_model
from random import shuffle



class AdminTemplateView(TemplateView):
    template_name = 'shop/admin/admin.html'

    def get_template_names(self):
        user = get_user_model()
        admin = user.objects.get(username='staff')
        if self.request.user == admin:
            return ['shop/admin/admin.html']
        else:
            raise PermissionError

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['total'] = 5
    #     return context


class ProductListByCategory(ListView):
    model = Product
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context['categories'] = categories
        context['current_page'] = 'shop:products'
        context['filterset'] = self.filterset

        user = get_user_model()
        admin = user.objects.get(username='staff')

        if self.request.user == admin:
            products_admin = Product.objects.all()
            context['products_admin'] = products_admin

        return context

    def get_queryset(self):
        if not self.kwargs.get('slug'):
            queryset = Product.objects.all()
        else:
            # Получаем категорию по slug из URL
            category = get_object_or_404(Category, slug=self.kwargs['slug'])
            queryset = Product.objects.filter(category=category)

        query = self.request.GET.get('query')
        self.query = query
        if query:
            queryset = queryset.filter(Q(name__icontains=query))

        self.filterset = ProductFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_template_names(self):
        user = get_user_model()
        admin = user.objects.get(username='staff')

        if self.request.user == admin:
            return ['shop/admin/products.html']
        else:
            return ['shop/products_by_category.html']

    def get_paginate_by(self, queryset):
        user = get_user_model()
        admin = user.objects.get(username='staff')

        if self.request.user != admin:
            return 3
        return None


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductCreateForm
    template_name = 'shop/admin/product_add.html'
    success_url = reverse_lazy('shop:products')


class ProductDetailView(DetailView):
    model = Product
    template_name = ('shop/admin/product_detail.html')
    context_object_name = 'product'
    slug_url_kwarg = 'slug'

    def get_template_names(self):
        user = get_user_model()
        admin = user.objects.get(username='staff')
        if self.request.user == admin:
            return ['shop/admin/product_detail.html']
        else:
            return ['shop/product_detail.html']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.object.category

        products = []
        for pr in category.products.all():
            if pr != self.object:
                products.append(pr)

        shuffle(products)
        products = products[:2]
        # products = category.products.all()[:2]
        context['products'] = products

        return context


class ProductListView(ListView):
    model = Product
    template_name = 'shop/admin/products.html'
    context_object_name = 'products'


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'shop/admin/product_edit.html'
    form_class = ProductCreateForm
    # fields = ["category", "name", "description", "image", "price", "available"]
    success_url = reverse_lazy('shop:products')
    slug_url_kwarg = 'slug'


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'shop/admin/product_delete.html'
    success_url = reverse_lazy('shop:products')
    slug_url_kwarg = 'slug'


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryCreateForm
    template_name = 'shop/admin/category_add.html'
    success_url = reverse_lazy('shop:categories')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = 'categories'
        return context


class CategoryListView(ListView):
    model = Category
    context_object_name = 'categories'

    def get_template_names(self):
        user = get_user_model()
        admin = user.objects.get(username='staff')
        if self.request.user == admin:
            return ['shop/admin/categories.html']
        else:
            return ['shop/categories.html']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'shop:categories'

        return context


class CategoryDetailView(DetailView):
    model = Category
    context_object_name = 'category'
    slug_url_kwarg = 'slug'

    def get_template_names(self):
        user = get_user_model()
        admin = user.objects.get(username='staff')
        if self.request.user == admin:
            return ['shop/admin/category_detail.html']
        else:
            return ['shop/category_detail.html']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.object
        products = category.products.all()[:2]
        context['products'] = products

        return context


def about(request):
    context = {
        'name': 'Книжный',
        'type': '---ИНТЕРНЕТ-МАГАЗИН---',
        'city': 'Санкт-Петербург',
        'year': '2024',
        'pr_name': 'Алина',
        'pr_lastname': 'Бурлова',
        'pr_email': 'alina-burlova@bk.ru',
        'current_page': 'shop:about',
    }

    return render(request, template_name='shop/about.html', context=context)


class CategoryUpdateView(UpdateView):
    model = Category
    template_name = 'shop/admin/category_edit.html'
    form_class = CategoryCreateForm
    # fields = ["name"]
    success_url = reverse_lazy('shop:categories')
    slug_url_kwarg = 'slug'


class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'shop/admin/category_delete.html'
    success_url = reverse_lazy('shop:categories')
    slug_url_kwarg = 'slug'


def product_search(request, category):
    query = request.GET.get('query', '')
    query_text = Q(name__contains=query)

    if category != 'all':
        category_obj = Category.objects.get(slug=category)
        results = Product.objects.filter(query_text, category=category_obj)
    else:
        results = Product.objects.filter(query_text)

    filterset = ProductFilter(request.GET, results)

    categories = Category.objects.all()

    paginator = Paginator(filterset.qs, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'categories': categories,
        'page_obj': page_obj,
        'filterset': filterset,
        'is_paginated': paginator.num_pages > 1,
        'query': query,
        'current_page': 'shop:products',
    }

    return render(request, template_name="shop/products_by_category.html", context=context)


# def product_list_view(request, slug):
#     categories = Category.objects.all()
#     if slug:
#         category = get_object_or_404(Category, slug=slug)
#         products_by_category = Product.objects.filter(category=category)
#         filterset = ProductFilter(request.GET, queryset=products_by_category)
#         context = {"products": filterset.qs, 'filterset': filterset, "categories": categories}
#         return render(request, template_name="shop/products_by_category.html", context=context)
#
#     queryset = Product.objects.all()
#     filterset = ProductFilter(request.GET, queryset=queryset)
#     context = {"products": filterset.qs, 'filterset': filterset, "categories": categories}
#
#     return render(request, template_name="shop/products_by_category.html", context=context)

def forbidden(request, exception):
    return render(request, "403.html", status=403)


def page_not_found(request, exception):
    return render(request, "404.html", status=404)


def server_error(request):
    return render(request, "500.html", status=500)

shop/templates/shop/admin/categories.html
{% extends 'base_admin.html' %}
{% block title %}
<title>Список категорий</title>
{% endblock title %}
{% block content %}
<h2 class="book_h2">Список категорий</h2>
<ol>
  {% for category in categories %}
  <li><a class="admin-slk" href="{{ category.get_absolute_url }}">{{category.name}}</a></li>
  {% endfor %}
</ol>
{% endblock content %}

shop/templates/shop/admin/category_add.html
{% extends 'base_admin.html' %}
{% block title %}
<title>Добавление категории</title>
{% endblock title %}
{% block content %}
<h2 class="book_h2">Добавление категории</h2>
<form method="post" enctype="multipart/form-data" class="user-form">
  {% csrf_token %}
    <div class="fields">
    {% for field in form %}
    <div class="text-field">
      <span class="text-field__label">{{field.label_tag}}</span>
      {{field}}
    </div>
    {% endfor %}
  </div>
  <button type="submit" class="btn btn-light">Добавить категорию</button>
</form>
{% endblock content %}

shop/templates/shop/admin/category_delete.html
{% extends 'base_admin.html' %}
{% block title %}
<title>{{category.name}}</title>
{% endblock title %}
{% block content %}
<h2 class="book_h2">Удаление категории</h2>
<div style="width: 70%; margin: 0 auto; margin-top: 10%;">
<h3 class="book_h2" style="text-align: center;">Вы действительно хотите удалить следующую категорию?</h3>
<p style="text-align: center;"><b>Все товары из этой категории будут удалены!</b></p>
<hr />
<div>Наименование категории - {{category.name}}</div>
<hr />
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Удалить</button>
  <a href="{% url 'shop:categories' %}" class="btn btn-light">Отмена</a>
</form>
</div>

{% endblock content %}

shop/templates/shop/admin/category_detail.html
{% extends 'base_admin.html' %}
{% block title %}
<title>{{category.name}}</title>
{% endblock title %}
{% block content %}
<h2 class="book_h2">Категория - {{category.name}}</h2>

<p>Краткая информация о категории</p>
<div>
  {{category.description}}
</div>

<a href="{% url 'shop:category_edit' slug=category.slug %}" class="btn btn-light"
  >Изменить категорию</a
>
<a href="{% url 'shop:category_delete' slug=category.slug %}" class="btn btn-danger"
  >Удалить категорию</a
>

{% endblock content %}

shop/templates/shop/admin/category_edit.html
{% extends 'base_admin.html' %}
{% block title %}
<title>Изменение категории</title>
{% endblock title %}
{% block content %}
<h2 class="book_h2">Изменение категории</h2>
<form method="post" enctype="multipart/form-data" class="user-form">
  {% csrf_token %}
    <div class="fields">
    {% for field in form %}
    <div class="text-field">
      <span class="text-field__label">{{field.label_tag}}</span>
      {{field}}
    </div>
    {% endfor %}
  </div>
  <button type="submit" class="btn btn-light">Изменить категорию</button>
</form>
{% endblock content %}

shop/templates/shop/admin/category_update.html
{% extends 'base_admin.html' %}

{% block title %}
<title>Изменение категории</title>
{% endblock title %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Изменить категорию</button>
</form>
{% endblock content %}

shop/templates/shop/admin/orders.html
{% extends 'base_admin.html' %}
{% load static %}
{% block title %}
<title>Все заказы</title>
{% endblock title %}
{% block content %}
<h2 class="book_h2">Таблица заказов</h2>
<div class="cart-detail" style="max-height: 500px;">
<table>
  <thead >
    <tr>
      <th class="order-header" style="color: black; background-color: white">Номер заказа</th>
      <th class="order-header" style="color: black; background-color: white">Пользователь</th>
      <th class="order-header" style="color: black; background-color: white">Способ оплаты</th>
      <th class="order-header" style="color: black; background-color: white">Способ доставки</th>
      <th class="order-header" style="color: black; background-color: white">Дата</th>
    </tr>
  </thead>
  <tbody>
    {% for order in orders %}
    <tr>
      <td class="order-number">
        <a href="{% url 'order_detail' order.number %}" style="color: white;">{{ order.number }}</a>
      </td>
      <td class="order-delivery">{{ order.user }}</td>
      <td class="order-payment">{{ order.payment }}</td>
      <td class="order-delivery">{{ order.delivery }}</td>
      <td class="order-date">{{ order.created_at }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock content %}

shop/templates/shop/admin/product_add.html
{% extends 'base_admin.html' %}
{% block title %}
<title>Добавление товара</title>
{% endblock title %}
{% block content %}
<h2 class="book_h2">Добавление товара</h2>
<form method="post" enctype="multipart/form-data" class="user-form">
  {% csrf_token %}
    <div class="fields">
    {% for field in form %}
    <div class="text-field">
      <span class="text-field__label">{{field.label_tag}}</span>
      {{field}}
    </div>
    {% endfor %}
  </div>
  <button type="submit" class="btn btn-light">Добавить товар</button>
</form>
{% endblock content %}

shop/templates/shop/admin/product_delete.html
{% extends 'base_admin.html' %}
{% block title %}
<title>{{product.name}}</title>
{% endblock title %}
{% block content %}
<h2 class="book_h2">Удаление товара</h2>
<div style="width: 70%; margin: 0 auto; margin-top: 10%;">
<h3 class="book_h2" style="text-align: center;">Вы действительно хотите удалить следующий товар?</h3>
<hr />
<div>Автор - {{product.author}}</div>
<div>Название книги - {{product.name}}</div>
<div>Стоимость - {{product.price}}</div>
<hr />
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Удалить</button>
  <a href="{% url 'shop:products' %}" class="btn btn-light">Отмена</a>
</form>

{% endblock content %}

shop/templates/shop/admin/product_detail.html
{% extends 'base_admin.html' %}
{% block title %}
<title>{{product.name}}</title>
{% endblock title %}
{% block content %}
<h2 class="book_h2">Книга #{{product.id}}</h2>
<p>Краткая информация о товаре</p>
<div>Автор - {{product.author}}</div>
<div>Название книги - '{{product.name}}'</div>
<div>Описание - {{product.description}}</div>
<div>Стоимость - {{product.price}}</div>

<a href="{% url 'shop:product_edit' slug=product.slug %}" class="btn btn-light">Изменить товар</a>
<a href="{% url 'shop:product_delete' slug=product.slug %}" class="btn btn-danger">Удалить товар</a>

{% endblock content %}

shop/templates/shop/admin/product_edit.html
{% extends 'base_admin.html' %}
{% block title %}
<title>Изменение товара</title>
{% endblock title %}
{% block content %}
<h2 class="book_h2">Изменение товара</h2>
<form method="post" enctype="multipart/form-data" class="user-form">
  {% csrf_token %}
    <div class="fields">
    {% for field in form %}
    <div class="text-field">
      <span class="text-field__label">{{field.label_tag}}</span>
      {{field}}
    </div>
    {% endfor %}
  </div>
  <button type="submit" class="btn btn-light">Изменить товар</button>
</form>
{% endblock content %}

shop/templates/shop/admin/products.html
{% extends 'base_admin.html' %}
{% load static %}
{% load custom_tags %}
{% block title %}
<title>Список товаров</title>
{% endblock title %}
{% block content %}
<h2 class="book_h2">Список товаров</h2>
<ol>
  {% for product in products_admin %}
  <li><a class="admin-slk" href="{{ product.get_absolute_url }}">{{product.author}} '{{product.name}}'</a></li>
  {% endfor %}
</ol>

{% endblock content %}