cart/urls.py
from django.urls import path
from .views import cart_detail, update_cart_by_front, remove_product, remove_cart, get_cart_length, remove_product_ajax

app_name = 'cart'

urlpatterns = [
    path('detail/', cart_detail, name='cart_detail'),
    path('update_cart_session/', update_cart_by_front, name='update_cart_session'),
    path('remove_fetch/', remove_product_ajax, name="remove_product_ajax"),
    path('remove/<int:product_id>/', remove_product, name="remove_product"),
    path('clear/', remove_cart, name="remove_cart"),
    path('length/', get_cart_length, name="cart_length"),
]

shop/urls.py
from django.urls import path
from .views import (ProductListView, ProductCreateView, ProductDetailView,
                    ProductUpdateView, ProductDeleteView,
                    CategoryCreateView, CategoryListView, CategoryDetailView,
                    CategoryUpdateView, CategoryDeleteView)
from .views import ProductListByCategory, product_search, about
# from .views import product_list_view
from cart.views import cart_add

app_name = 'shop'

urlpatterns = [
    # path('categories/<slug:slug>/products/test/', product_list_view, name='test'),

    path('about/', about, name='about'),

    path('categories/add/', CategoryCreateView.as_view(), name='category_add'),
    path('categories/<slug:slug>/edit/', CategoryUpdateView.as_view(), name='category_edit'),
    path('categories/<slug:slug>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('categories/<slug:slug>/products/', ProductListByCategory.as_view(), name='products_by_category'),
    path('categories/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('categories/', CategoryListView.as_view(), name='categories'),

    path('search/', product_search, name='product_search'),
    path('search/<str:category>/', product_search, name="product_search"),
    path('search/all/', product_search, name="product_search"),



    path('list/', ProductListByCategory.as_view(), name='products'),
    path('add/', ProductCreateView.as_view(), name='product_add'),
    path('<slug:slug>/edit/', ProductUpdateView.as_view(), name='product_edit'),
    path('<slug:slug>/addToCart/', cart_add, name='add_to_cart'),
    path('<slug:slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),


    path('', ProductListByCategory.as_view(), name='index'),


]

users/urls.py
from django.urls import path
from .views import (register, log_in, log_out, user_detail, change_password, change_profile)
# from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('log_in/', log_in, name='login'),
    path('log_out/', log_out, name='logout'),
    path('default/<int:pk>', user_detail, name='detail'),
    path('change_password/', change_password, name='change_password'),
    path('change_profile/', change_profile, name='change_profile'),
    # path('log_out/', LogoutView.as_view(next_page=""), name='logout'),
]

website_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop.views import AdminTemplateView, ProductListByCategory
from website_shop import settings
from orders.views import all_order_list

urlpatterns = [
    path('staff/orders/', all_order_list, name="admin_all_orders"),
    path('staff/', AdminTemplateView.as_view(), name="admin-page"),
    path('admin/', admin.site.urls),
    path('products/', include('shop.urls')),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', ProductListByCategory.as_view(), name='main'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = "shop.views.forbidden"
handler404 = "shop.views.page_not_found"
handler500 = "shop.views.server_error"

cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from shop.models import Product

User = get_user_model()


class CartUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class CartItem(models.Model):
    cart = models.ForeignKey(CartUser, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

cart/views.py
import json
from itertools import product

from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from decimal import Decimal

from django.views.decorators.csrf import csrf_exempt

from shop.models import Product
from website_shop.settings import CART_SESSION_ID

from .models import CartUser, CartItem

class Cart:
    def __init__(self, request):
        # получаем текущую сессию
        self.session = request.session
        # получаем текущего пользователя
        self.user = request.user
        # получаем корзину из сессии или создаем новую
        cart = self.session.get(CART_SESSION_ID)
        # создаем новую корзину
        if not cart:
            cart = self.session[CART_SESSION_ID] = {}
        self.cart = cart

    # сохранение изменений в сессию
    def save(self):
        self.session.modified = True

    # метод помещения товара в корзину
    def add(self, product, quantity=1, override_quantity=False):
        # получаем id товара из ОБЪЕКТА товара
        product_id = str(product.id)

        if product_id not in self.cart:
            self.cart[product_id] = {
                'quantity': 0,
                'price': str(product.price)
            }

        if override_quantity:
            self.cart[product_id]['quantity'] = quantity
        else:
            self.cart[product_id]['quantity'] += quantity

        self.save()

    # удаление товара из корзины
    def remove(self, product):

        product_id = str(product.id)
        if product_id in self.cart:
            del self.cart[product_id]
            self.save()

    # метод подсчета общего количества элементов в корзине
    def __len__(self):
        return sum(item['quantity'] for item in self.cart.values())
        # return len(self.cart) - количество товаров в корзмне (без учета кол-ва каждого товара)

    def get_total_price(self):
        return sum(Decimal(item['price']) * item['quantity'] for item in self.cart.values())

    def clear(self):
        self.cart.clear()
        # del self.session[CART_SESSION_ID]
        self.save()

    def __iter__(self):
        product_ids = self.cart.keys()
        products = Product.objects.filter(id__in=product_ids)
        cart = self.cart.copy()

        for product in products:
            cart[str(product.id)]['product'] = product

        for item in cart.values():
            item['price'] = Decimal(item['price'])
            item['total_price'] = item['price'] * item['quantity']
            yield item


# корзина авторизованного пользователя
class ProductCartUser:
    def __init__(self, request):
        # получаем текущего пользователя
        self.user = request.user
        # получаем корзину пользователя из БД или создаем новую
        self.user_cart, created = CartUser.objects.get_or_create(user=self.user)
        # получаем позиции товаров в корзине
        products_in_cart = CartItem.objects.filter(cart=self.user_cart)
        # создаем объект для хранения товаров
        self.cart = {}

        for item in products_in_cart:
            self.cart[str(item.product_id)] = {'quantity': item.quantity, 'price': item.product.price}

    def add(self, product, quantity=1, override_quantity=False):
        product_id = str(product.id)
        if product_id not in self.cart:
            self.cart[product_id] = {
                'quantity': 0,
                'price': str(product.price)
            }

        if override_quantity:
            self.cart[product_id]['quantity'] = quantity
        else:
            self.cart[product_id]['quantity'] += quantity

        self.save()


    # метод сохранения корзины
    def save(self):
        for prod_id in self.cart:
            product = Product.objects.get(pk=prod_id)
            # проверяем наличие товара в БД
            # если есть - обновляем количество
            if CartItem.objects.filter(cart=self.user_cart, product=product).exists():
                item = CartItem.objects.get(cart=self.user_cart, product=product)
                item.quantity = self.cart[prod_id]['quantity']
                item.save()
            # иначе - создаем новую позицию
            else:
                CartItem.objects.create(cart=self.user_cart, product=product, quantity=self.cart[prod_id]['quantity'])

    def clear(self):
        self.user_cart.items.all().delete()  # Удаляем все позиции из корзины
        self.cart.clear()  # Очищаем локальную корзину
        self.user_cart.save()  # Сохраняем изменения в корзине пользователя

    def remove(self, product_id, request):
        product = Product.objects.get(pk=product_id)
        cart_user = CartUser.objects.get(user=request.user)
        cart_item = CartItem.objects.get(cart=cart_user, product=product)
        cart_item.delete()

    def __iter__(self):
        product_ids = self.cart.keys()
        products = Product.objects.filter(id__in=product_ids)
        cart = self.cart.copy()

        for product in products:
            cart[str(product.id)]['product'] = product

        for item in cart.values():
            item['price'] = Decimal(item['price'])
            item['total_price'] = item['price'] * item['quantity']
            yield item

    def get_total_price(self):
        return sum(Decimal(item['price']) * item['quantity'] for item in self.cart.values())

    def __len__(self):
        return sum(item['quantity'] for item in self.cart.values())


def cart_add(request, slug):
    product = get_object_or_404(Product, slug=slug)

    # создаем корзину (получаем из сессии)
    if request.user.id:
        cart = ProductCartUser(request)
    else:
        cart = Cart(request)

    cart.add(product=product)

    return redirect('shop:index')


def cart_detail(request):
    context = {
        'current_page': 'cart:cart_detail',
    }

    return render(request, template_name='cart/cart_detail.html', context=context)


@csrf_exempt
def update_cart_by_front(request):
    data = json.loads(request.body)
    print(data)
    print(type(data))
    product_id = data.get('productIdValue')
    quantity = data.get('quantityValue')

    if product_id:
        cart = Cart(request)

        product = get_object_or_404(Product, pk=int(product_id))
        cart.add(product=product, quantity=int(quantity), override_quantity=True)
        print('ok', cart.cart)
        response_data = {'result': 'success'}
    else:
        response_data = {'result': 'failed'}

    return JsonResponse(response_data)


def remove_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.user.id:
        cart = ProductCartUser(request)
        cart.remove(product_id, request)
    else:
        cart = Cart(request)
        cart.remove(product)

    return redirect("cart:cart_detail")


def remove_cart(request):
    if request.user.id:
        cart = ProductCartUser(request)
    else:
        cart = Cart(request)

    cart.clear()

    return redirect("cart:cart_detail")


def get_cart_length(request):
    cart = Cart(request)
    cart_length = len(cart)
    print(cart_length)
    response_data = {"cart_length": cart_length}
    return JsonResponse(response_data)


@csrf_exempt
def remove_product_ajax(request):
    data = json.loads(request.body)
    product_id = data.get('productIdValue')
    product = get_object_or_404(Product, pk=product_id)
    if request.user.id:
        cart = ProductCartUser(request)
        cart.remove(product_id, request)
    else:
        cart = Cart(request)
        cart.remove(product)

    response_data = {'result': 'success'}
    return JsonResponse(response_data)

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
{% if cart|length != 0 %}
<h2 class="cart-h2">Корзина</h2>
<div class="cart-detail">
  <table>
    <thead>
      <tr>
        <th class="delete">№</th>
        <th class="delete">Изображение</th>
        <th>Наименование</th>
        <th>Цена</th>
        <th>Количество</th>
        <th>Стоимость</th>
        <th>Удалить</th>
        <th class="delete cross-del">Быстрое удаление</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
      {% with product=item.product %}
      <tr>
        <input type="hidden" value="{{product.id}}" id="productId" />
        <td style="text-align: center" class="delete">{{ forloop.counter }}</td>
        <td style="text-align: center" class="delete">
          {% if product.image %}
          <img
            src="{{ product.image.url }}"
            alt="{{ product.name }}"
            style="width: 30px; height: 30px"
          />
          {% else %}
          <img
            src="{% static 'img/no_image.png' %}"
            class="card-img-top"
            alt="{{ product.name }}"
            style="width: 30px; height: 30px"
          />
          {% endif %}
        </td>
        <td>{{ product.name }}</td>
        <td style="text-align: center">
          <span id="productPrice">{{ product.price|floatformat:0 }}</span> руб.
        </td>
        <td style="text-align: center">
          <input
            style="width: 100%"
            id="prod_quantity"
            name="prod_quantity"
            type="number"
            min="1"
            max="100000"
            value="{{ item.quantity }}"
          />
        </td>
        <td style="text-align: center">
          <span id="itemPrice">{{ item.total_price|floatformat:0 }}</span> руб.
        </td>
        <td style="text-align: center">
          <a href="{% url 'cart:remove_product' product.id %}"
            ><img style="width: 30px" src="{% static 'img/cross.png' %}"
          /></a>
        </td>
        <td style="text-align: center" class="delete cross-del">
          <button
            class="removeFetch btn btn-danger"
            style="padding: 0.5px 5px; margin-top: 0"
          >
            ***
          </button>
        </td>
      </tr>
      {% endwith %}
      {% endfor %}
    </tbody>
  </table>
</div>

<div class="card-price">
  <div style="flex-direction: column">
    <div>Товаров в корзине: <span id="cartLength">{{ cart|length }}</span></div>
    <div>
      Сумма товаров в корзине:
      <span id="totalPriceCart">{{ cart.get_total_price|floatformat:0 }}</span>
    </div>
    <a href="{% url 'cart:remove_cart' %}" class="btn btn-secondary cart-btn"
      >Очистить корзину</a
    >
  </div>

  <div style="padding-top: 10px">
    {% if not request.user.id %}
    <a href="#" class="btn btn-primary cart-btn" id="newOrder"
      >Оформить заказ</a
    >
    {% else %}
    <a
      href="{% url 'new_order' %}"
      class="btn btn-primary cart-btn"
      id="newOrderUser"
      >Оформить</a
    >
    {% endif %}
  </div>
</div>

<div id="orderModal" class="modal-my">
  <div class="modal-content-my">
    <span class="close" id="closeOrder">&times;</span>
    <h4 style="margin-top: 7px">Войдите или купите в 1 клик</h4>
    <a href="{% url 'users:login' %}" id="login" class="btn btn-primary"
      >Войти</a
    >
    <a href="#" id="quickOrderBtn" class="btn btn-primary">Купить в 1 клик</a>
  </div>
</div>

<div id="orderFormModal" class="modal-my__order-form">
  <div class="modal-content-my__order-form">
    <span class="close" id="closeOrderForm">&times;</span>
    <h4>Заполните информацию о заказе</h4>
    <form action="#" method="post" class="order-choice modal-choice">
      {{ quick_order_form.as_p }}
      {% csrf_token %}
      <input
        type="button"
        id="createQuickOrderBtn"
        value="Оформить"
        class="btn btn-secondary"
      />
    </form>
  </div>
</div>

{% else %}

<p class="cart-empty">Корзина пуста😭</p>

{% endif %}

<script>
  async function removeItemFetch(event) {
    let productId =
      event.target.parentElement.parentElement.querySelector(
        "#productId"
      ).value;

    let itemInfo = {
      productIdValue: productId,
    };

    let response = await fetch("/cart/remove_fetch/", {
      method: "POST",
      headers: {
        "Content-Type": "application/json;charset=utf-8",
      },
      body: JSON.stringify(itemInfo),
    });
  }

  async function removeItem(event) {
    await removeItemFetch(event);
    afterRemoveItem(event.target.parentElement.parentElement);
    setTimeout(updatePrice.bind(null, event), 2000);
  }

  async function getCartLength() {
    let response = await fetch("/cart/length/", {
      method: "GET",
      headers: {
        "Content-Type": "application/json;charset=utf-8",
      },
    });

    let result = await response.json();
    alert("Товаров в корзине: " + result.cart_length);
  }

  function getTotalPriceCart() {
    let itemPriceInputs = document.querySelectorAll("#itemPrice");
    let totalPrice = 0;
    itemPriceInputs.forEach((item, index) => {
      totalPrice += +item.textContent;
    });
    let totalPriceCart = document.querySelector("#totalPriceCart");
    totalPriceCart.textContent = totalPrice;
    return totalPrice;
  }

  function getQuantityInCart() {
    let cartLengthHeader = document.querySelector("#cartLengthHeader");
    let quantityInputs = document.querySelectorAll("#prod_quantity");
    let allQuantity = 0;
    quantityInputs.forEach((item, index) => {
      allQuantity += +item.value;
    });
    let cartLength = document.querySelector("#cartLength");
    cartLength.textContent = allQuantity;
    cartLengthHeader.textContent = allQuantity;
    return allQuantity;
  }

  function updatePrice(event) {
    let quantity = event.target.value;
    let itemPrice =
      event.target.parentElement.parentElement.querySelector("#itemPrice");
    let productPrice =
      event.target.parentElement.parentElement.querySelector(
        "#productPrice"
      ).textContent;
    productPrice = Number(productPrice.replace(",", "."));

    let newItemPrice = productPrice * quantity;
    itemPrice.textContent = newItemPrice;
    getQuantityInCart();
    getTotalPriceCart();
  }

  function afterRemoveItem(item) {
    item.remove();
  }

  async function saveCartInSession(event) {
    let productId =
      event.target.parentElement.parentElement.querySelector(
        "#productId"
      ).value;
    let quantity = event.target.value;

    let cartInfo = {
      productIdValue: productId,
      quantityValue: quantity,
      totalQuantity: getQuantityInCart(),
      totalPrice: getTotalPriceCart(),
    };

    let response = await fetch("/cart/update_cart_session/", {
      method: "POST",
      headers: {
        "Content-Type": "application/json;charset=utf-8",
      },
      body: JSON.stringify(cartInfo),
    });

    let result = await response.json();
  }
  const quantityInput = document.querySelectorAll("#prod_quantity");
  quantityInput.forEach((item) => {
    item.addEventListener("change", updatePrice);
  });
  quantityInput.forEach((item) => {
    item.addEventListener("change", saveCartInSession);
  });

  const newOrderBtn = document.querySelector("#newOrder");
  // newOrderBtn.addEventListener('click', getCartLength)

  const itemsRemove = document.querySelectorAll(".removeFetch");
  itemsRemove.forEach((item) => {
    item.addEventListener("click", removeItem);
  });

  // ===================== ORDER MODAL =====================
  // Получаем элемент модального окна
  const orderModal = document.getElementById("orderModal");
  const orderFormModal = document.getElementById("orderFormModal");

  // Получаем кнопку для открытия модального окна
  const orderBtn = document.querySelector("#newOrder");
  const quickOrderBtn = document.querySelector("#quickOrderBtn");

  // Получаем элемент закрытия модального окна
  const closeOrder = document.getElementById("closeOrder");
  const closeOrderForm = document.getElementById("closeOrderForm");

  // Открываем модальное окно для заказа
  orderBtn.onclick = function () {
    orderModal.style.display = "block";
  };

  // Открываем модальное окно для быстрого заказа
  quickOrderBtn.onclick = function () {
    orderFormModal.style.display = "block";
    orderModal.style.display = "none";
  };

  // Закрытие модального окна для заказа
  closeOrder.onclick = function () {
    orderModal.style.display = "none";
  };

  // Закрываем модальное окно для быстрого заказа
  closeOrderForm.onclick = function () {
    orderFormModal.style.display = "none";
  };

  // Закрываем модальное окно при клике вне его области
  window.onclick = function (event) {
    if (event.target === orderModal) {
      orderModal.style.display = "none";
    }
    if (event.target === orderFormModal) {
      orderFormModal.style.display = "none";
    }
  };

  // ===================== CREATE QUICK ORDER =====================
  const createQuickOrderBtn = document.querySelector("#createQuickOrderBtn");

  async function createQuickOrder(event) {
    const myForm = event.target.parentElement;
    const name = myForm.name.value;
    const lastName = myForm.last_name.value;
    const email = myForm.email.value;
    const phone = myForm.phone.value;
    const payment = myForm.payment.value;
    const delivery = myForm.delivery.value;

    let orderInfo = {
      name: name,
      lastName: lastName,
      email: email,
      phone: phone,
      payment: payment,
      delivery: delivery,
    };

    let response = await fetch("/orders/new/quick/", {
      method: "POST",
      headers: {
        "Content-Type": "application/json;charset=utf-8",
      },
      body: JSON.stringify(orderInfo),
    });

    let result = await response.json();
    alert("Заказ успешно создан!");
    window.location.replace("{% url 'shop:index' %}");
  }

  createQuickOrderBtn.addEventListener("click", createQuickOrder);
</script>
{% endblock content %}