cart/urls.py
from django.urls import path
from .views import cart_detail, update_cart_by_front, remove_product, remove_cart, get_cart_length, remove_product_ajax

app_name = 'cart'

urlpatterns = [
    path('detail/', cart_detail, name='cart_detail'),
    path('update_cart_session/', update_cart_by_front, name='update_cart_session'),
    path('remove_fetch/', remove_product_ajax, name="remove_product_ajax"),
    path('remove/<int:product_id>/', remove_product, name="remove_product"),
    path('clear/', remove_cart, name="remove_cart"),
    path('length/', get_cart_length, name="cart_length"),
]

users/urls.py
from django.urls import path
from .views import (register, log_in, log_out, user_detail, change_password, change_profile)
# from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('log_in/', log_in, name='login'),
    path('log_out/', log_out, name='logout'),
    path('default/<int:pk>', user_detail, name='detail'),
    path('change_password/', change_password, name='change_password'),
    path('change_profile/', change_profile, name='change_profile'),
    # path('log_out/', LogoutView.as_view(next_page=""), name='logout'),
]

website_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop.views import AdminTemplateView, ProductListByCategory
from website_shop import settings
from orders.views import all_order_list

urlpatterns = [
    path('staff/orders/', all_order_list, name="admin_all_orders"),
    path('staff/', AdminTemplateView.as_view(), name="admin-page"),
    path('admin/', admin.site.urls),
    path('products/', include('shop.urls')),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', ProductListByCategory.as_view(), name='main'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = "shop.views.forbidden"
handler404 = "shop.views.page_not_found"
handler500 = "shop.views.server_error"

users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    city = models.CharField(max_length=100, verbose_name="Город")
    image = models.ImageField(upload_to="users/", blank=True, null=True, verbose_name="Изображение")

users/forms.py
from django import forms
from django.contrib.auth import get_user_model


User = get_user_model()


class UserRegistrationForm(forms.ModelForm):

    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)

    def clean_password2(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['password'] != cleaned_data['password2']:
            raise forms.ValidationError('Пароли не совпадают!')
        return cleaned_data['password2']

    class Meta:
        model = User
        fields = ('username', 'password',
                  'first_name', 'last_name', 'email',
                  'phone', 'city', 'image')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username',
                  'first_name', 'last_name', 'email',
                  'phone', 'city', 'image']


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput, label='Старый пароль')
    new_password = forms.CharField(widget=forms.PasswordInput, label='Новый пароль')
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Подтверждение нового пароля')

    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data.get('old_password')
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        # Проверка на совпадение нового пароля со старым
        if old_password == new_password:
            self.add_error('new_password', 'Новый пароль не должен совпадать со старым.')

        # Проверка на совпадение нового пароля с подтверждением
        if new_password != confirm_password:
            self.add_error('confirm_password', 'Пароли не совпадают.')

        return cleaned_data

users/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages

from cart.views import Cart, ProductCartUser
from website_shop.settings import LOGIN_REDIRECT_URL
from .forms import UserRegistrationForm, ChangePasswordForm, UserProfileForm

from orders.models import Order

User = get_user_model()


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            context = {
                'title': 'Успешная регистрация',
                'new_user': new_user,
            }
            return render(request, template_name='users/register_done.html', context=context)
    user_form = UserRegistrationForm()
    context = {
        'register_form': user_form,
        'current_page': 'users:register',
    }
    return render(request, template_name='users/register.html', context=context)


def log_in(request):
    form = AuthenticationForm(request, request.POST)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            url = request.GET.get('next', LOGIN_REDIRECT_URL)
            cart = Cart(request)
            cart_user = ProductCartUser(request)
            cart_user.cart.update(cart.cart)
            cart_user.save()
            return redirect(url)
    context = {'form': form, 'current_page': 'users:login'}
    return render(request, template_name='users/login.html', context=context)


@login_required
def log_out(request):
    logout(request)
    return redirect('shop:products')

@login_required
def user_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    orders = Order.objects.filter(user=user)
    order_count = orders.count()

    if request.user != user:
        raise PermissionDenied()
    context = {
        'user': user,
        'title': 'Информация о профиле',
        'order_count': order_count,
        'current_page': 'users:detail',
    }

    admin = get_user_model().objects.get(username='staff')
    if request.user == admin:
        return render(request, template_name='users/admin/admin.html', context=context)

    return render(request, template_name='users/profile.html', context=context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['new_password']

            # Проверка правильности старого пароля
            if not request.user.check_password(old_password):
                form.add_error('old_password', 'Старый пароль неверен.')
            else:
                # Изменение пароля
                request.user.set_password(new_password)
                request.user.save()
                update_session_auth_hash(request, request.user)  # Сохраняем сессию пользователя
                messages.success(request, 'Пароль успешно изменен.')
                return redirect('some_view')  # Замените на нужный вам URL

    else:
        form = ChangePasswordForm()

    return render(request, 'users/change_password.html', {'form': form})


@login_required
def change_profile(request):
    user = request.user
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            form.save()
            context = {
                'user': user,
                'title': 'Успешное изменение профиля',
            }
            return render(request, template_name='users/change_done.html', context=context)
    else:
        form = UserProfileForm(instance=user)

    context = {
        'form': form,
        'title': 'Изменение профиля',
    }

    return render(request, 'users/change_profile.html', context=context)

users/templates/users/change_done.html
{% extends 'base.html' %}
{% block title %}
<title>{{title}}</title>
{% endblock title %}
{% block content %}
<h2
  style="
    text-align: center;
    padding-top: 15%;
    width: fit-content;
    margin: 0 auto;
  "
>
  Пользователь {{ user.username }} успешно изменен
</h2>

{% endblock content %}

users/templates/users/change_password.html
{% extends 'base.html' %}
{% block content %}

<h2 class="password-h2">Изменение пароля</h2>

<form method="post" class="password-form">
    {% csrf_token %}
    <div class="fields">
		{% for field in form %}
		<div class="text-field">
			<span class="text-field__label">{{field.label_tag}}</span>
			{{field}}
        </div>
        {% if field.errors %}
        <span>Исправьте ошибки в поле:</span>
        <div class="error-list">
            <ul>
                {% for error in field.errors %}
                <li>{{error}}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% endfor %}
    <button type="submit" class="btn btn-primary" style="margin: 20px 0;">Изменить</button>
</form>

{% endblock content %}

users/templates/users/change_profile.html
{% extends 'base.html' %}
{% block title %}
<title>Изменение профиля</title>
{% endblock title %}
{% block content %}

<h2 class="user-p">{{ title }}</h2>

<div class="container">
  <form method="post" enctype="multipart/form-data" class="user-form">
    {% csrf_token %}
    <div class="fields">
      {% for field in form %}
      <div class="text-field">
        <span class="text-field__label">{{field.label_tag}}</span>
        {{field}}
      </div>
      {% endfor %}
    </div>

    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
  </form>
</div>

{% endblock content %}

users/templates/users/login.html
{% extends 'base.html' %}
{% block title %}
<title>Вход</title>
{% endblock title %}

{% block content %}


<form method="post" class="user-form login-form">
    {% csrf_token %}
    <h2>Пожалуйста, войдите на сайт</h2>
        <div class="fields">
			{% for field in form %}
			<div class="text-field">
				<span class="text-field__label">{{field.label_tag}}</span>
				{{field}}
			</div>
			{% endfor %}
    <button type="submit" class="btn btn-primary">Войти</button>
</form>

{% endblock content %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h2 class="user-h2">Ваш профиль</h2>
<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
  <div class="user-card card p-4">
    <div
      class="image d-flex flex-column justify-content-center align-items-center"
    >
      <button class="btn btn-secondary btn-new">
        {% if user.image %}
        <img
          src="{{ user.image.url }}"
          alt="{{ user.username }}"
          height="100"
          width="100"
          style="object-fit: cover"
        />
        {% else %}
        <img
          src="{% static 'img/no_image_people.png' %}"
          alt="{{ user.username }}"
          height="100"
          width="100"
          style="object-fit: cover"
        />
        {% endif %}
      </button>
      <span class="name name-1 mt-3">{{ user.username }}</span>
      <span class="name">{{ user.last_name }} {{ user.first_name }}</span>
      <span class="mail">{{ user.email }}</span>
      <div
        class="d-flex flex-row justify-content-center align-items-center gap-2"
      >
        <span class="tel">{{ user.phone }}</span>
      </div>
      <div
        class="d-flex flex-row justify-content-center align-items-center mt-3"
      >
        <a href="{% url 'orders' %}" class="orders"
          ><span class="orders-span"
            >{{ order_count }} <span class="follow">заказа/ов</span></span
          ></a
        >
      </div>
      <div class="d-flex mt-2 btns">
        <a href="{% url 'users:change_profile' %}" class="btn btn1 btn-dark"
          >Изменить профиль</a
        >
        <a href="{% url 'users:change_password' %}" class="btn btn1 btn-dark"
          >Изменить пароль</a
        >
      </div>
      <div class="px-2 rounded mt-4 date">
        <span class="join"
          >Дата создания: {{ user.date_joined|date:"F j, Y" }}</span
        >
      </div>
    </div>
  </div>
</div>

{% endblock content %}

users/templates/users/register.html
{% extends 'base.html' %}
{% block title %}
<title>Регистрация</title>
{% endblock title %} {% block content %}
<h2 class="user-p">Регистрация</h2>
<form method="post" class="user-form">
  {% csrf_token %}
  <div class="fields">
    {% for field in register_form %}
    <div class="text-field">
      <span class="text-field__label">{{field.label_tag}}</span>
      {{field}}
    </div>
    {% endfor %}
  </div>
  <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
</form>

{% endblock content %}

users/templates/users/register_done.html
{% extends 'base.html' %}
{% block title %}
<title>Успешная регистрация</title>
{% endblock title %}
{% block content %}
<h2
  style="
    text-align: center;
    padding-top: 15%;
    width: fit-content;
    margin: 0 auto;
  "
>
  Пользователь {{ new_user.username }} успешно зарегистрирован!
</h2>

{% endblock content %}