cart/urls.py
from django.urls import path
from .views import cart_detail, update_cart_by_front, remove_product, remove_cart, get_cart_length, remove_product_ajax

app_name = 'cart'

urlpatterns = [
    path('detail/', cart_detail, name='cart_detail'),
    path('update_cart_session/', update_cart_by_front, name='update_cart_session'),
    path('remove_fetch/', remove_product_ajax, name="remove_product_ajax"),
    path('remove/<int:product_id>/', remove_product, name="remove_product"),
    path('clear/', remove_cart, name="remove_cart"),
    path('length/', get_cart_length, name="cart_length"),
]

shop/urls.py
from django.urls import path
from .views import (ProductListView, ProductCreateView, ProductDetailView,
                    ProductUpdateView, ProductDeleteView,
                    CategoryCreateView, CategoryListView, CategoryDetailView,
                    CategoryUpdateView, CategoryDeleteView)
from .views import ProductListByCategory, product_search, about
# from .views import product_list_view
from cart.views import cart_add

app_name = 'shop'

urlpatterns = [
    # path('categories/<slug:slug>/products/test/', product_list_view, name='test'),

    path('about/', about, name='about'),

    path('categories/add/', CategoryCreateView.as_view(), name='category_add'),
    path('categories/<slug:slug>/edit/', CategoryUpdateView.as_view(), name='category_edit'),
    path('categories/<slug:slug>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('categories/<slug:slug>/products/', ProductListByCategory.as_view(), name='products_by_category'),
    path('categories/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('categories/', CategoryListView.as_view(), name='categories'),

    path('search/', product_search, name='product_search'),
    path('search/<str:category>/', product_search, name="product_search"),
    path('search/all/', product_search, name="product_search"),



    path('list/', ProductListByCategory.as_view(), name='products'),
    path('add/', ProductCreateView.as_view(), name='product_add'),
    path('<slug:slug>/edit/', ProductUpdateView.as_view(), name='product_edit'),
    path('<slug:slug>/addToCart/', cart_add, name='add_to_cart'),
    path('<slug:slug>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),


    path('', ProductListByCategory.as_view(), name='index'),


]

users/urls.py
from django.urls import path
from .views import (register, log_in, log_out, user_detail, change_password, change_profile)
# from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('log_in/', log_in, name='login'),
    path('log_out/', log_out, name='logout'),
    path('default/<int:pk>', user_detail, name='detail'),
    path('change_password/', change_password, name='change_password'),
    path('change_profile/', change_profile, name='change_profile'),
    # path('log_out/', LogoutView.as_view(next_page=""), name='logout'),
]

website_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop.views import AdminTemplateView, ProductListByCategory
from website_shop import settings
from orders.views import all_order_list

urlpatterns = [
    path('staff/orders/', all_order_list, name="admin_all_orders"),
    path('staff/', AdminTemplateView.as_view(), name="admin-page"),
    path('admin/', admin.site.urls),
    path('products/', include('shop.urls')),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', ProductListByCategory.as_view(), name='main'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = "shop.views.forbidden"
handler404 = "shop.views.page_not_found"
handler500 = "shop.views.server_error"

templates/base.html
{% load static %}
{% load custom_tags %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    {% block title %}
    <title>Магазин товаров</title>
    {% endblock title %}
</head>
<body>
    <header>
         <nav class="header">
          <div class="left">
        <a href="{% url 'shop:categories' %}" class="{% if current_page == 'shop:categories' %}active{% endif %}" > Категории</a>
        <a href="{% url 'shop:products' %}" class="{% if current_page == 'shop:products' %}active{% endif %}">Товары</a>
        <a href="{% url 'shop:about' %}" class="{% if current_page == 'shop:about' %}active{% endif %}">О нас</a>
        {% if cart|length != 0 %}
        <a href="{% url 'cart:cart_detail' %}" class="{% if current_page == 'cart:cart_detail' %}active{% endif %}">Корзина (<span id="cartLengthHeader">{{ cart|length }}</span>)</a>
        {% else %}
        <a href="{% url 'cart:cart_detail' %}" class="{% if current_page == 'cart:cart_detail' %}active{% endif %}">Корзина<span id="cartLengthHeader"></span></a>
        {% endif %}
        <a href="{% url 'orders' %}" class="{% if current_page == 'orders' %}active{% endif %}">Заказы</a>
          </div>


          <div class="nav-item dropdown right left-small">
              <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'img/menu.png' %}" width="20px">
          </a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarScrollingDropdown">
              <a href="{% url 'shop:categories' %}" class="dropdown-item {% if current_page == 'shop:categories' %}active{% endif %}">Категории</a>
            <a  href="{% url 'shop:products' %}" class="dropdown-item {% if current_page == 'shop:products' %}active{% endif %}" >Товары</a>
            <a  href="{% url 'shop:about' %}" class="dropdown-item {% if current_page == 'shop:about' %}active{% endif %}">О нас</a>
            {% if cart|length != 0 %}
            <a  href="{% url 'cart:cart_detail' %}" class="dropdown-item {% if current_page == 'cart:cart_detail' %}active{% endif %}">Корзина (<span id="cartLengthHeader">{{ cart|length }}</span>)</a>
             {% else %}
            <a  href="{% url 'cart:cart_detail' %}" class="dropdown-item {% if current_page == 'cart:cart_detail' %}active{% endif %}">Корзина<span id="cartLengthHeader"></span></a>
              {% endif %}
            <a href="{% url 'orders' %}" class="dropdown-item {% if current_page == 'orders' %}active{% endif %}">Заказы</a>
          </div>


        <div class="nav-item dropdown right">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'img/people.png' %}" width="20px">
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarScrollingDropdown">
              {% if not user.is_authenticated %}
            <li><a href="{% url 'users:register' %}" class="dropdown-item {% if current_page == 'users:register' %}active{% endif %}">Регистрация</a></li>
            <li><a href="{% url 'users:login' %}" class="dropdown-item {% if current_page == 'users:login' %}active{% endif %}">Войти</a></li>
              {% endif %}
              {% if user.is_authenticated %}
            <li><a href="{% url 'users:logout' %}" class="dropdown-item">Выйти</a></li>
            <li><a href="{% url 'users:detail' pk=user.pk %}" class="dropdown-item {% if current_page == 'users:detail' %}active{% endif %}">{{ user.username }}</a></li>
              {% endif %}
          </ul>
              </div>
    </nav>

    </header>
    <form class="search" action="{% url 'shop:product_search' request.path|category_path %}" method="get">
        <input type="search" name="query" value="{{ query|default:'' }}">
        <button type="submit" class="btn btn-secondary" style="padding: 3px 5px; margin: 0;">Поиск</button>
    </form>
		<div class="my_block">
    {% block content %}

    {% endblock content%}
	</div>

    <footer>
        <p>Контактные данные: info@example.com | Телефон: +7 (123) 456-78-90</p>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
</body>
</html>

templates/base_admin.html
{% load static %}
{% load custom_tags %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    {% block title %}
    <title>Магазин товаров</title>
    {% endblock title %}
</head>
<body style="background-color: #333; color: #fff;">
    <header class="admin-header">
         <nav class="header" style="background-color: #fff; color: #000;">
          <div class="left">
            <a href="{% url 'shop:category_add' %}" style="color: #000;">Добавить категорию</a>
            <a href="{% url 'shop:categories' %}" style="color: #000;">Категории</a>
            <a href="{% url 'shop:product_add' %}" style="color: #000;">Добавить товар</a>
            <a href="{% url 'shop:products' %}" style="color: #000;">Товары</a>
            <a href="{% url 'admin_all_orders' %}" style="color: #000;">Заказы</a>
          </div>


          <div class="nav-item dropdown right left-small">
              <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'img/menu-dark.png' %}" width="20px">
          </a>
              <ul class="dropdown-menu drop-1" aria-labelledby="navbarScrollingDropdown">
                  <a href="{% url 'shop:category_add' %}" style="color: #000;">Добавить категорию</a><br>
                  <a href="{% url 'shop:categories' %}" style="color: #000;">Категории</a><br>
                  <a href="{% url 'shop:product_add' %}" style="color: #000;">Добавить товар</a><br>
                  <a href="{% url 'shop:products' %}" style="color: #000; ">Товары</a><br>
                  <a href="{% url 'admin_all_orders' %}" style="color: #000; ">Заказы</a>
              </ul>
          </div>

        <div class="nav-item dropdown right">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'img/people-dark.png' %}" width="20px">
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a href="{% url 'users:logout' %}" class="dropdown-item" style="color: #000;">Выйти</a></li>
            <li><a href="{% url 'users:detail' pk=user.pk %}" class="dropdown-item" style="color: #000;">{{ user.username }}</a></li>
          </ul>
              </div>
    </nav>

    </header>

    <div class="my_block">
    {% block content %}

    {% endblock content%}
	</div>

    <footer style="background-color: #fff; color: #000;">
        <p>Телефон тех. поддержки: +7 (987) 654-32-10</p>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
</body>
</html>